lib: [
  "_build/install/default/lib/bsmi_ocaml/META"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml.a"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml.cma"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml.cmi"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml.cmt"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml.cmx"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml.cmxa"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml.ml"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml__Netrc.cmi"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml__Netrc.cmt"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml__Netrc.cmti"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml__Netrc.cmx"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml__Timeutils.cmi"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml__Timeutils.cmt"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml__Timeutils.cmti"
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml__Timeutils.cmx"
  "_build/install/default/lib/bsmi_ocaml/dune-package"
  "_build/install/default/lib/bsmi_ocaml/netrc.ml"
  "_build/install/default/lib/bsmi_ocaml/netrc.mli"
  "_build/install/default/lib/bsmi_ocaml/opam"
  "_build/install/default/lib/bsmi_ocaml/timeutils.ml"
  "_build/install/default/lib/bsmi_ocaml/timeutils.mli"
]
libexec: [
  "_build/install/default/lib/bsmi_ocaml/bsmi_ocaml.cmxs"
]
bin: [
  "_build/install/default/bin/bsmi_ocaml"
  "_build/install/default/bin/bsmi_ocaml_hello"
]
doc: [
  "_build/install/default/doc/bsmi_ocaml/LICENSE"
]
